spring:
  profiles:
    active: test
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated  # 用来配置消息发送到交换器之后是否触发回调方法
    publisher-returns: true   # 触发路由失败消息的回调(用不上)
    listener:
      simple:
        acknowledge-mode: manual  #手动确认
       # prefetch: 1    #限流（海量数据，同时只能过来一条）
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    host: 127.0.0.1
    port: 6379
    database: 1
    password:
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1

